#Importing All Required Libraries

In [75]:
import numpy as np
import pandas as pd

#Loading the dataset(Training & Testing)

In [76]:
df=pd.read_csv("/content/drive/MyDrive/train.csv")
df.head(10)

0         1         2  ...       560  Subject  activity
0  0.288585 -0.020294 -0.132905  ... -0.058627        1         5
1  0.278419 -0.016411 -0.123520  ... -0.054317        1         5
2  0.279653 -0.019467 -0.113462  ... -0.049118        1         5
3  0.279174 -0.026201 -0.123283  ... -0.047663        1         5
4  0.276629 -0.016570 -0.115362  ... -0.043892        1         5
5  0.277199 -0.010098 -0.105137  ... -0.042126        1         5
6  0.279454 -0.019641 -0.110022  ... -0.043010        1         5
7  0.277432 -0.030488 -0.125360  ... -0.041976        1         5
8  0.277293 -0.021751 -0.120751  ... -0.037364        1         5
9  0.280586 -0.009960 -0.106065  ... -0.034417        1         5

[10 rows x 563 columns]

#Data Preparation

In [77]:
df.shape

(7352, 563)

In [78]:

df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '553', '554', '555', '556', '557', '558', '559', '560', 'Subject',
       'activity'],
      dtype='object', length=563)

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7352 entries, 0 to 7351
Columns: 563 entries, 0 to activity
dtypes: float64(561), int64(2)
memory usage: 31.6 MB


In [80]:
df.isna().sum()

0           0
1           0
2           0
3           0
4           0
           ..
558         0
559         0
560         0
Subject     0
activity    0
Length: 563, dtype: int64

In [81]:
df=df.drop('Subject',axis=1)
df.head(10)

0         1         2  ...       559       560  activity
0  0.288585 -0.020294 -0.132905  ...  0.179941 -0.058627         5
1  0.278419 -0.016411 -0.123520  ...  0.180289 -0.054317         5
2  0.279653 -0.019467 -0.113462  ...  0.180637 -0.049118         5
3  0.279174 -0.026201 -0.123283  ...  0.181935 -0.047663         5
4  0.276629 -0.016570 -0.115362  ...  0.185151 -0.043892         5
5  0.277199 -0.010098 -0.105137  ...  0.184823 -0.042126         5
6  0.279454 -0.019641 -0.110022  ...  0.182170 -0.043010         5
7  0.277432 -0.030488 -0.125360  ...  0.183779 -0.041976         5
8  0.277293 -0.021751 -0.120751  ...  0.188982 -0.037364         5
9  0.280586 -0.009960 -0.106065  ...  0.190310 -0.034417         5

[10 rows x 562 columns]

In [82]:
df['activity'].value_counts()

6    1407
5    1374
4    1286
1    1226
2    1073
3     986
Name: activity, dtype: int64

#Model Part

In [83]:
from sklearn.model_selection import train_test_split
x=np.array(df.drop('activity',axis=1))
y=np.array(df.activity.tolist())
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.30,random_state=0)

In [84]:
X_train.shape

(5146, 561)

In [85]:
y_train.shape

(5146,)

In [86]:
X_test.shape

(2206, 561)

In [87]:
y_test.shape

(2206,)

In [88]:
import xgboost as xgb
from xgboost.sklearn import XGBClassifier
model=XGBClassifier()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

#Metrics


##Accuracy

In [89]:
from sklearn.metrics import accuracy_score
print("Accuracy : "+str(accuracy_score(y_test,y_pred)))

Accuracy : 0.9873073436083409


##Classification Report

In [90]:
from sklearn.metrics import classification_report
print("Classification Report : "+str(classification_report(y_test,y_pred)))

Classification Report :               precision    recall  f1-score   support

           1       0.99      0.99      0.99       361
           2       0.99      1.00      1.00       315
           3       1.00      0.99      0.99       280
           4       0.98      0.97      0.97       406
           5       0.97      0.98      0.97       409
           6       1.00      1.00      1.00       435

    accuracy                           0.99      2206
   macro avg       0.99      0.99      0.99      2206
weighted avg       0.99      0.99      0.99      2206



##Confusion Metrics

In [91]:
from sklearn.metrics import confusion_matrix
print("Accuracy : \n"+str(confusion_matrix(y_test,y_pred)))

Accuracy : 
[[359   2   0   0   0   0]
 [  0 315   0   0   0   0]
 [  2   1 277   0   0   0]
 [  0   0   0 392  14   0]
 [  0   0   0   9 400   0]
 [  0   0   0   0   0 435]]


##F1-Score

In [92]:
from sklearn.metrics import f1_score
print("F1-Score : "+str(f1_score(y_test,y_pred,average='macro')))

F1-Score : 0.9879812240424272


#Saving the Model


In [93]:
import pickle

In [94]:
pickle.dump(model,open("model_{{model name}}.pkl","wb+"),protocol=pickle.HIGHEST_PROTOCOL)